sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - develop # build master branch only
script:
  - cp -ip ./_config.theme.yml ./themes/icarus/_config.yml
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: develop
  local-dir: public
  target_branch: master
